### ISSUE TITLE
IPv6 bug

### ISSUE THREAD

**Issue by acbekoac** [sdcampbell/goscan#1]
Hi,
this is a nice IPv6 bug

./goscan --all-ports $MY_IP6_PREFIX:0:0:0:0/64
scanme.nmap.org:80
scanme.nmap.org:22

I do not own, the IPv6 address space of nmap.org ;)

**Comment by sdcampbell** [comment]
What is the bug? Please demonstrate how there's a bug in goscan. Thanks

**Comment by acbekoac** [comment]
./goscan --all-ports 2a02:a46c:c839:1:0:0:0:0/64
scanme.nmap.org:80
scanme.nmap.org:22

dig +noall +answer scanme.nmap.org aaaa
scanme.nmap.org.	3600	IN	AAAA	2600:3c01::f03c:91ff:fe18:bb2f

--> not my IPv6 Adress space, so I stop to not scan a foreign target

**Comment by sdcampbell** [comment]
I fixed it. I updated the readme to say "Goscan is a standalone, fast **IPv4** TCP scanner...". Closing
